# Generated by Django 2.2.1 on 2019-05-16 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190516_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_date',
            field=models.DateField(default=datetime.date(2019, 5, 16)),
        ),
    ]
