# Generated by Django 2.2.1 on 2019-05-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_date',
            field=models.DateField(default='django.utils.timezone.now'),
        ),
    ]
