# Generated by Django 2.2.1 on 2019-06-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190622_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, upload_to='profie_pic'),
        ),
    ]
