# Generated by Django 2.2.1 on 2019-05-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
    ]
