# Generated by Django 2.2.1 on 2019-06-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190622_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.FileField(blank=True, upload_to='myapp/static/client_pic/'),
        ),
    ]
